# Generated by Django 3.2.8 on 2021-10-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoalCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='StatusTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('unique_id', models.CharField(max_length=50)),
                ('pwd', models.CharField(max_length=30)),
                ('user_type', models.IntegerField(choices=[(0, 'Supervisor'), (1, 'Staff'), (2, 'Patient')], default=2)),
                ('insurance_information', models.CharField(max_length=1000)),
            ],
        ),
    ]
