# Generated by Django 3.2.8 on 2021-11-12 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('goal', models.CharField(default=None, max_length=400)),
                ('statusofgoal', models.IntegerField(choices=[(0, 'NotCompletedGoal'), (1, 'NotAdequate'), (2, 'Adequate'), (3, 'ExceedsAdequacy'), (4, 'Great')], default=0)),
                ('notesforgoal', models.CharField(default=None, max_length=400)),
                ('goalcurrency', models.IntegerField(choices=[(0, 'Completed Goal'), (1, 'Current Goal'), (2, 'Future Goal')], default=2)),
                ('userforgoal', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='capstone_project.user')),
            ],
        ),
        migrations.DeleteModel(
            name='GoalCurrency',
        ),
    ]
