# Generated by Django 3.2.8 on 2021-12-03 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_project', '0003_auto_20211202_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statustable',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
